const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const FORBIDDEN_ERROR = 403;
const CONFLICT_ERROR = 409;
const AUTHORIZATION_ERROR = 401;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  FORBIDDEN_ERROR,
  CONFLICT_ERROR,
  AUTHORIZATION_ERROR,
};
